# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181022_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='group', to='users.Group'),
        ),
    ]
